In [1]:
import numpy as np

In [3]:
mu,sigma=0.0,1.0
g=np.random.normal(loc=mu,scale=sigma,size=1000)
g1=np.random.randn(1000)

In [5]:
g=(g-g.min())/10
phy=np.round(((100.1-20)*g+20),1)
g1=(g1-g1.min())/10
mat=np.round(((100.1-20)*g1+20),1)

In [7]:
phy

array([52.6, 60.3, 58.2, 40.4, 56.1, 44.5, 61.5, 57.9, 54.6, 43.7, 42.3,
       48.5, 43.8, 57.3, 50.9, 55. , 45.1, 45. , 49.7, 36.4, 47.7, 54.4,
       47.5, 62.5, 51.7, 32.3, 28.7, 44.6, 44.9, 46.5, 53.5, 47. , 57.3,
       52.7, 33.3, 52.2, 35.8, 53.9, 45.1, 55.2, 49. , 53. , 46.4, 45.3,
       31.6, 43.4, 35.6, 47.4, 46.5, 44.3, 56.6, 44. , 44.3, 49.6, 47.8,
       41.5, 55.2, 39. , 34.6, 29.7, 48.4, 61.6, 46.6, 52.9, 53.9, 36.6,
       46. , 57.8, 45.6, 39. , 48.4, 36.3, 64.4, 53.9, 50.4, 33.2, 48.8,
       52. , 45.7, 44.4, 35.2, 47.8, 57. , 34.9, 47.6, 50.2, 43.7, 43.8,
       54.2, 38. , 50.2, 48.8, 56.1, 52.6, 61.2, 49.9, 43.5, 54.9, 48.5,
       48.3, 46.8, 38.6, 40.7, 43.7, 36.9, 43.9, 56. , 54.8, 33.7, 40.6,
       49.7, 54. , 54.5, 48.8, 53. , 34.4, 30.7, 43.5, 51. , 42.1, 41.7,
       38.6, 55.2, 36.4, 57.8, 52.9, 56.4, 42.9, 49.5, 44.6, 61.4, 47.3,
       53.4, 47.4, 38.8, 42.6, 48.2, 47. , 40.4, 38.7, 54.6, 41.5, 51.7,
       50. , 44.3, 56. , 32.2, 48.3, 57.1, 37.8, 30

In [8]:
mat

array([47.1, 42.3, 56.7, 34.1, 45.4, 37. , 60.9, 52.8, 45.9, 46.9, 41.1,
       44.9, 54.6, 44.5, 44.2, 57.8, 35.3, 43.1, 52.3, 57.9, 33.6, 35.2,
       56.7, 45. , 53. , 35. , 36.9, 27.3, 54.3, 41.2, 41. , 61.9, 28.1,
       47.4, 42.1, 51.8, 44.7, 42. , 50.2, 50.4, 41.9, 45.3, 50.5, 38.6,
       50. , 50.1, 40.6, 44.2, 30.2, 56.5, 47.9, 46.5, 34. , 42.5, 39.1,
       39.4, 33.1, 45.2, 58.7, 47. , 44.4, 46.1, 51.4, 36.8, 48.4, 45.2,
       50.8, 50. , 42. , 49.5, 53.4, 54.3, 58. , 41.8, 63.7, 52.7, 49. ,
       33.2, 51.7, 47.3, 55.2, 44.2, 37.5, 28.5, 43. , 37.6, 45.3, 31.4,
       46. , 49.7, 57.4, 41.1, 43.7, 54.5, 50.8, 42.7, 42.8, 42.1, 36.7,
       31.9, 49.6, 51.9, 49.5, 44. , 52. , 53.3, 50.1, 56.1, 31.2, 56.9,
       48.9, 52.9, 43.8, 33.4, 56.3, 40.6, 39.2, 37.1, 41.1, 39.2, 33.3,
       49.4, 37.8, 55.3, 56.6, 55.7, 49.6, 49.2, 35.2, 52.1, 49.3, 39.3,
       46.8, 37.9, 45.6, 44.8, 40.9, 30.8, 43.4, 47. , 39.1, 48.9, 53.9,
       43.3, 39. , 58. , 53.2, 45.4, 47.4, 54.7, 35

In [6]:
np.mean(phy)

46.801700000000004

In [9]:
np.std(phy)

7.908775323019361

In [10]:
np.min(phy),np.max(phy)

(20.0, 71.5)

In [11]:
np.percentile(phy,80)

53.52

In [12]:
np.median(phy)

47.3

In [13]:
marks=np.vstack((phy,mat))
marks  # 生成1000名学生的物理与数学成绩

array([[52.6, 60.3, 58.2, ..., 44.4, 49.7, 33.9],
       [47.1, 42.3, 56.7, ..., 34.9, 42. , 48.4]])

In [14]:
marks.shape

(2, 1000)

In [16]:
np.mean(marks,axis=1)  # 沿1轴计算平均值，得到物理与数学的平均值

array([46.8017, 44.6282])

In [17]:
np.mean(marks,axis=0)  # 沿0轴计算每个人总成绩的平均值

array([49.85, 51.3 , 57.45, 37.25, 50.75, 40.75, 61.2 , 55.35, 50.25,
       45.3 , 41.7 , 46.7 , 49.2 , 50.9 , 47.55, 56.4 , 40.2 , 44.05,
       51.  , 47.15, 40.65, 44.8 , 52.1 , 53.75, 52.35, 33.65, 32.8 ,
       35.95, 49.6 , 43.85, 47.25, 54.45, 42.7 , 50.05, 37.7 , 52.  ,
       40.25, 47.95, 47.65, 52.8 , 45.45, 49.15, 48.45, 41.95, 40.8 ,
       46.75, 38.1 , 45.8 , 38.35, 50.4 , 52.25, 45.25, 39.15, 46.05,
       43.45, 40.45, 44.15, 42.1 , 46.65, 38.35, 46.4 , 53.85, 49.  ,
       44.85, 51.15, 40.9 , 48.4 , 53.9 , 43.8 , 44.25, 50.9 , 45.3 ,
       61.2 , 47.85, 57.05, 42.95, 48.9 , 42.6 , 48.7 , 45.85, 45.2 ,
       46.  , 47.25, 31.7 , 45.3 , 43.9 , 44.5 , 37.6 , 50.1 , 43.85,
       53.8 , 44.95, 49.9 , 53.55, 56.  , 46.3 , 43.15, 48.5 , 42.6 ,
       40.1 , 48.2 , 45.25, 45.1 , 43.85, 44.45, 48.6 , 53.05, 55.45,
       32.45, 48.75, 49.3 , 53.45, 49.15, 41.1 , 54.65, 37.5 , 34.95,
       40.3 , 46.05, 40.65, 37.5 , 44.  , 46.5 , 45.85, 57.2 , 54.3 ,
       53.  , 46.05,

In [19]:
np.std(marks,axis=1)  # 计算1轴上的标准差

array([7.90877532, 7.81138687])

In [20]:
#  获取物理成绩大于平均值的同学
phy[phy>np.mean(phy)]

array([52.6, 60.3, 58.2, 56.1, 61.5, 57.9, 54.6, 48.5, 57.3, 50.9, 55. ,
       49.7, 47.7, 54.4, 47.5, 62.5, 51.7, 53.5, 47. , 57.3, 52.7, 52.2,
       53.9, 55.2, 49. , 53. , 47.4, 56.6, 49.6, 47.8, 55.2, 48.4, 61.6,
       52.9, 53.9, 57.8, 48.4, 64.4, 53.9, 50.4, 48.8, 52. , 47.8, 57. ,
       47.6, 50.2, 54.2, 50.2, 48.8, 56.1, 52.6, 61.2, 49.9, 54.9, 48.5,
       48.3, 56. , 54.8, 49.7, 54. , 54.5, 48.8, 53. , 51. , 55.2, 57.8,
       52.9, 56.4, 49.5, 61.4, 47.3, 53.4, 47.4, 48.2, 47. , 54.6, 51.7,
       50. , 56. , 48.3, 57.1, 59.9, 47.3, 57.2, 50. , 59.6, 51.7, 55.2,
       53.6, 49.2, 56. , 56.4, 65. , 56.5, 53.6, 52.1, 50.5, 50.2, 49.7,
       47.6, 53.2, 54.5, 61.8, 68. , 56.1, 51.6, 50.7, 48.5, 49.1, 55.1,
       49.4, 55.6, 47.1, 53.2, 55.7, 55.2, 49.9, 57.7, 65.2, 54.7, 55.9,
       49.4, 52. , 62.8, 54.3, 62.8, 54. , 56.9, 51.1, 71.5, 48.9, 55.5,
       59.7, 54. , 61.4, 51.9, 50.2, 55.9, 51.5, 48.2, 47.2, 51.4, 57.4,
       52.5, 59.8, 50.4, 49.3, 55.3, 50.9, 47.5, 46

In [21]:
np.where(phy>mat,1,-1)  # 三元判断运算，第二个参数是为True时，第三个是为False时

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1,
        1, -1, -1,  1,  1, -1,  1, -1, -1, -1,  1, -1,  1,  1, -1,  1,  1,
       -1,  1, -1,  1, -1,  1,  1,  1, -1,  1, -1, -1, -1,  1,  1, -1,  1,
       -1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1, -1,  1,  1, -1, -1,  1,
        1, -1, -1, -1,  1,  1, -1, -1, -1,  1, -1, -1, -1,  1,  1,  1,  1,
        1, -1,  1,  1, -1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1, -1, -1, -1,  1, -1,  1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,
        1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,  1,  1,  1, -1, -1,
        1,  1, -1, -1,  1, -1, -1,  1,  1, -1, -1,  1,  1, -1, -1,  1, -1,
       -1,  1,  1, -1,  1, -1, -1, -1, -1,  1, -1,  1,  1, -1,  1, -1,  1,
        1,  1,  1,  1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1,  1,
        1,  1, -1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1,
        1,  1,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1,
       -1, -1, -1,  1,  1

In [22]:
grand_a=np.mean(phy)+20
grand_b=np.mean(phy)
grand_a,grand_b

(66.80170000000001, 46.801700000000004)

In [23]:
# select 实现分段函数的功能，分段统计。
np.select([phy>=grand_a,np.logical_and(phy>=grand_b,phy<=grand_a)],['A','B'],default='C')

array(['B', 'B', 'B', 'C', 'B', 'C', 'B', 'B', 'B', 'C', 'C', 'B', 'C',
       'B', 'B', 'B', 'C', 'C', 'B', 'C', 'B', 'B', 'B', 'B', 'B', 'C',
       'C', 'C', 'C', 'C', 'B', 'B', 'B', 'B', 'C', 'B', 'C', 'B', 'C',
       'B', 'B', 'B', 'C', 'C', 'C', 'C', 'C', 'B', 'C', 'C', 'B', 'C',
       'C', 'B', 'B', 'C', 'B', 'C', 'C', 'C', 'B', 'B', 'C', 'B', 'B',
       'C', 'C', 'B', 'C', 'C', 'B', 'C', 'B', 'B', 'B', 'C', 'B', 'B',
       'C', 'C', 'C', 'B', 'B', 'C', 'B', 'B', 'C', 'C', 'B', 'C', 'B',
       'B', 'B', 'B', 'B', 'B', 'C', 'B', 'B', 'B', 'C', 'C', 'C', 'C',
       'C', 'C', 'B', 'B', 'C', 'C', 'B', 'B', 'B', 'B', 'B', 'C', 'C',
       'C', 'B', 'C', 'C', 'C', 'B', 'C', 'B', 'B', 'B', 'C', 'B', 'C',
       'B', 'B', 'B', 'B', 'C', 'C', 'B', 'B', 'C', 'C', 'B', 'C', 'B',
       'B', 'C', 'B', 'C', 'B', 'B', 'C', 'C', 'C', 'C', 'C', 'B', 'C',
       'B', 'B', 'C', 'C', 'C', 'B', 'B', 'C', 'B', 'B', 'C', 'B', 'C',
       'B', 'B', 'B', 'C', 'B', 'B', 'B', 'C', 'C', 'C', 'B', 'C