In [1]:
import numpy as np

# 创建矩阵

In [3]:
A=np.mat([1,2,3])
A

matrix([[1, 2, 3]])

In [4]:
A.shape

(1, 3)

In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a.shape
# 由上可知数组可以是任何维度，矩阵是二维的

(3,)

In [9]:
B=np.mat('1 2 3;4 5 6;7 8 9')
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
C=np.mat(a)
C

matrix([[1, 2, 3]])

In [14]:
M1=np.mat(np.eye(2))
M2=M1*2
D=np.bmat('M1 M2;M2 M1')
D

matrix([[1., 0., 2., 0.],
        [0., 1., 0., 2.],
        [2., 0., 1., 0.],
        [0., 2., 0., 1.]])

# 矩阵乘法

In [19]:
a=np.arange(1,10).reshape((3,3))
b=np.array([[1,0,1],[0,1,1],[1,1,0]])

In [20]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
b

array([[1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [22]:
a*b  # 数组乘法

array([[1, 0, 3],
       [0, 5, 6],
       [7, 8, 0]])

In [23]:
A=np.mat(a)
B=np.mat(b)

In [24]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
B

matrix([[1, 0, 1],
        [0, 1, 1],
        [1, 1, 0]])

In [26]:
A*B  # 矩阵乘法不同于数组的乘法,矩阵乘法，A的对应行对应元素乘以B对应列对应元素后加和作为该位置元素

matrix([[ 4,  5,  3],
        [10, 11,  9],
        [16, 17, 15]])

In [27]:
np.dot(A,B)  # 效果同上

matrix([[ 4,  5,  3],
        [10, 11,  9],
        [16, 17, 15]])