In [1]:
import numpy as np
import time

# 计算

In [2]:
lst=[1,20,28,37,18,56]
[i*3 for i in lst]

[3, 60, 84, 111, 54, 168]

In [3]:
a=np.array(lst)
a*3

array([  3,  60,  84, 111,  54, 168])

In [4]:
a=np.arange(10).reshape((2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
b=a+10
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
a-10

array([[-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1]])

In [7]:
a/10

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

In [8]:
a.shape,b.shape

((2, 5), (2, 5))

In [9]:
a+b

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [10]:
a-b

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [11]:
a*b

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [12]:
a/b

array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421]])

In [13]:
# 广播
# 满足广播条件的计算要求，两个数组的任意一个轴需要长度相同
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
m=np.arange(5)
m.shape,a.shape

((5,), (2, 5))

In [15]:
a+m

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [16]:
n=np.arange(1,3).reshape((-1,1))
a.shape,n.shape

((2, 5), (2, 1))

In [17]:
a+n

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

# 比较运算

In [18]:
np.array([6,4,3]) > np.array([9,5,1])  # 需要比较的数组大小相同，然后比较里面的每一个元素，最后得到的是一个bool类型的数组

array([False, False,  True])

In [19]:
# Numpy中的与或非是，logical_and,logical_or,logical_not,logical_xor
np.logical_or(np.array([True,False]),np.array([False,True]))

array([ True,  True])

In [20]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
# any,all
np.any(a>b)

False

In [23]:
np.all(a<b)

True

# 通用函数

In [24]:
alpha=np.linspace(-1,1,11)
alpha

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [25]:
np.pi

3.141592653589793

In [26]:
y=np.sin(np.pi*alpha)
y

array([-1.22464680e-16, -5.87785252e-01, -9.51056516e-01, -9.51056516e-01,
       -5.87785252e-01,  0.00000000e+00,  5.87785252e-01,  9.51056516e-01,
        9.51056516e-01,  5.87785252e-01,  1.22464680e-16])

In [27]:
np.round(y,decimals=3)

array([-0.   , -0.588, -0.951, -0.951, -0.588,  0.   ,  0.588,  0.951,
        0.951,  0.588,  0.   ])

In [28]:
a=np.array([3,6,9])
b=np.array([4,5,8])

In [29]:
np.add(a,b)

array([ 7, 11, 17])

In [30]:
a=np.arange(10,100,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [31]:
# 自定义通用函数
def bmi(height,weight):
    bmi_index=weight/height**2
    if bmi_index>18 and bmi_index<25:
        return 0
    elif bmi_index<=18:
        return -1
    else:
        return 1

In [32]:
bmi(1.55,45)

0

In [33]:
h=(2.2-1.4)*np.random.random_sample((10,))+1.4
h

array([1.56978691, 2.09655812, 1.81239558, 1.72284406, 1.96030894,
       1.99747836, 2.13237181, 2.07024171, 1.92718782, 1.86229189])

In [34]:
h=np.round(h,2)
h

array([1.57, 2.1 , 1.81, 1.72, 1.96, 2.  , 2.13, 2.07, 1.93, 1.86])

In [35]:
w=(96-30)*np.random.random_sample((10,))+30
w

array([39.06048899, 45.65659852, 81.54361917, 93.50537577, 42.4914347 ,
       80.89241238, 71.77961625, 50.90454585, 85.39570486, 66.35408359])

In [36]:
w=np.round(w,2)
w

array([39.06, 45.66, 81.54, 93.51, 42.49, 80.89, 71.78, 50.9 , 85.4 ,
       66.35])

In [37]:
# 使用自定义函数前需要使用frompyfunc()
# 该函数能将普通函数转换为数组可以使用的，其参数第一个为数组，第二个为参入的参数数，第三个是返回值个数
bmi_ufunc=np.frompyfunc(bmi,2,1)
bmi_ufunc(h,w)

array([-1, -1, 0, 1, -1, 0, -1, -1, 0, 0], dtype=object)

In [38]:
pow_ufunc=np.frompyfunc(pow,2,1)
a=np.arange(10)
pow_ufunc(a,a)

array([1, 1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489],
      dtype=object)