In [1]:
import numpy as np
import pandas as pd

In [2]:
g=np.array([27466.3,24899.3,19610.9,19492.4,17885.39,17558.76,15475.09,12170.2])
g

array([27466.3 , 24899.3 , 19610.9 , 19492.4 , 17885.39, 17558.76,
       15475.09, 12170.2 ])

In [3]:
gdp=pd.Series(g,index=['shanghai','beijing','guangzhou','shenzhen','tianjin','chongqing','suzhou','chengdu'])
gdp

shanghai     27466.30
beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
chongqing    17558.76
suzhou       15475.09
chengdu      12170.20
dtype: float64

In [4]:
gdp['chengdu']

12170.2

In [5]:
'shanghai' in gdp  # Series对象是类字典对象

True

In [6]:
'hangzhou' in gdp

False

In [7]:
gdp.keys()

Index(['shanghai', 'beijing', 'guangzhou', 'shenzhen', 'tianjin', 'chongqing',
       'suzhou', 'chengdu'],
      dtype='object')

In [8]:
gdp.index

Index(['shanghai', 'beijing', 'guangzhou', 'shenzhen', 'tianjin', 'chongqing',
       'suzhou', 'chengdu'],
      dtype='object')

In [9]:
list(gdp.items())

[('shanghai', 27466.3),
 ('beijing', 24899.3),
 ('guangzhou', 19610.9),
 ('shenzhen', 19492.4),
 ('tianjin', 17885.39),
 ('chongqing', 17558.76),
 ('suzhou', 15475.09),
 ('chengdu', 12170.2)]

In [10]:
gdp['hangzhou']=11050.5
gdp

shanghai     27466.30
beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
chongqing    17558.76
suzhou       15475.09
chengdu      12170.20
hangzhou     11050.50
dtype: float64

In [11]:
gdp[['chengdu','shanghai','tianjin']]  # 与Numpy的索引是list时一样的

chengdu     12170.20
shanghai    27466.30
tianjin     17885.39
dtype: float64

In [12]:
gdp[gdp>19000]  # 与Numpy的索引是一个Bool值数组是一样的

shanghai     27466.3
beijing      24899.3
guangzhou    19610.9
shenzhen     19492.4
dtype: float64

In [13]:
g=gdp['beijing':'chengdu'] # 两端都是闭合的
g

beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
chongqing    17558.76
suzhou       15475.09
chengdu      12170.20
dtype: float64

In [14]:
g['wuhan']=11111
g

beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
chongqing    17558.76
suzhou       15475.09
chengdu      12170.20
wuhan        11111.00
dtype: float64

In [15]:
gdp

shanghai     27466.30
beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
chongqing    17558.76
suzhou       15475.09
chengdu      12170.20
hangzhou     11050.50
dtype: float64

In [16]:
gdp[4]

17885.39

In [17]:
gdp[1:5]

beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
dtype: float64

In [18]:
# 小问题
s=pd.Series(np.random.randn(4),index=[1,3,5,7])
s

1   -0.346720
3   -1.087677
5   -0.978257
7   -1.704227
dtype: float64

In [19]:
print(s[1]) # 索引取数据如果使用了整数的标签索引，此时索引取值的位置索引就失效了
print('-----------')
print(s[1:3]) # 切片的时候打算用标签索引来切片，却被以位置索引的方式来切片了

-0.34672036052729205
-----------
3   -1.087677
5   -0.978257
dtype: float64


In [20]:
print(s.iloc[1])  # 专用于位置索引
print('-------------------------')
print(s.iloc[1:3])

-1.0876774285450448
-------------------------
3   -1.087677
5   -0.978257
dtype: float64


In [21]:
print(s.loc[1])  # 专用于标签索引
print('------------------------')
print(s.loc[1:3])

-0.34672036052729205
------------------------
1   -0.346720
3   -1.087677
dtype: float64


In [22]:
# 多级索引下Series的索引跟切片
gdp_index=[('shanghai',2015),('shanghai',2016),('beijing',2015),('beijing',2016),('guangzhou',2015),('guangzhou',2016)]
gdp_mind=pd.MultiIndex.from_tuples(gdp_index)
gdp=pd.Series([27466.3,24899.3,19610.9,19492.4,17885.39,17558.76],index=gdp_mind)
gdp

shanghai   2015    27466.30
           2016    24899.30
beijing    2015    19610.90
           2016    19492.40
guangzhou  2015    17885.39
           2016    17558.76
dtype: float64

In [23]:
g1=gdp['shanghai']
g1,type(g1)

(2015    27466.3
 2016    24899.3
 dtype: float64, pandas.core.series.Series)

In [24]:
# DataFrame对象的索引与切片
population=pd.Series([2415.27,2151.6,1270.88],index=['shanghai','beijing','guangzhou'])
population

shanghai     2415.27
beijing      2151.60
guangzhou    1270.88
dtype: float64

In [25]:
gdp=pd.Series([27466,24899,19611],index=['shanghai','beijing','guangzhou'])
gdp

shanghai     27466
beijing      24899
guangzhou    19611
dtype: int64

In [26]:
d=pd.DataFrame({'gdp':gdp,'pop':population})
d

gdp      pop
shanghai   27466  2415.27
beijing    24899  2151.60
guangzhou  19611  1270.88

In [27]:
d.values

array([[27466.  ,  2415.27],
       [24899.  ,  2151.6 ],
       [19611.  ,  1270.88]])

In [28]:
d.values[0]

array([27466.  ,  2415.27])

In [29]:
d.T

shanghai  beijing  guangzhou
gdp  27466.00  24899.0   19611.00
pop   2415.27   2151.6    1270.88

### 总结DataFrame索引切片

In [37]:
d

gdp      pop
shanghai   27466  2415.27
beijing    24899  2151.60
guangzhou  19611  1270.88

In [42]:
d['gdp']  # DataFrame要获取某列的数据 就直接在索引中放入columns名称

shanghai     27466
beijing      24899
guangzhou    19611
Name: gdp, dtype: int64

In [41]:
d.iloc[1]  # 利用位置索引获取index索引的数据

gdp    24899.0
pop     2151.6
Name: beijing, dtype: float64

In [50]:
d.iloc[1,1]

2151.6

In [35]:
d.iloc[1:3,:1]

gdp
beijing    24899
guangzhou  19611

In [52]:
d['beijing':'guangzhou'] # 利用index的标签索引来切片

gdp      pop
beijing    24899  2151.60
guangzhou  19611  1270.88

In [54]:
d[1:3]  # 利用index的位置索引来切片

gdp      pop
beijing    24899  2151.60
guangzhou  19611  1270.88

In [56]:
d.loc['beijing':'guangzhou']

gdp      pop
beijing    24899  2151.60
guangzhou  19611  1270.88

In [57]:
d.iloc[1:3]

gdp      pop
beijing    24899  2151.60
guangzhou  19611  1270.88

In [76]:
d.loc['shanghai','pop']

2415.27

In [81]:
d.loc['guangzhou':,'pop':]

pop
guangzhou  1270.88

In [85]:
d.iloc[2:,:1]

gdp
guangzhou  19611

In [89]:
d.iloc[0,1]

2415.27

In [92]:
d.loc['shanghai','gdp':]

gdp    27466.00
pop     2415.27
Name: shanghai, dtype: float64

In [97]:
d.iloc[0,0:]

gdp    27466.00
pop     2415.27
Name: shanghai, dtype: float64