In [1]:
import numpy as np
import pandas as pd

In [2]:
g=np.array([27466.3,24899.3,19610.9,19492.4,17885.39,17558.76,15475.09,12170.2])
g

array([27466.3 , 24899.3 , 19610.9 , 19492.4 , 17885.39, 17558.76,
       15475.09, 12170.2 ])

In [3]:
gdp=pd.Series(g,index=['shanghai','beijing','guangzhou','shenzhen','tianjin','chongqing','suzhou','chengdu'])
gdp

shanghai     27466.30
beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
chongqing    17558.76
suzhou       15475.09
chengdu      12170.20
dtype: float64

In [4]:
gdp['chengdu']

12170.2

In [5]:
'shanghai' in gdp

True

In [6]:
'hangzhou' in gdp

False

In [7]:
gdp.keys()

Index(['shanghai', 'beijing', 'guangzhou', 'shenzhen', 'tianjin', 'chongqing',
       'suzhou', 'chengdu'],
      dtype='object')

In [8]:
gdp.index

Index(['shanghai', 'beijing', 'guangzhou', 'shenzhen', 'tianjin', 'chongqing',
       'suzhou', 'chengdu'],
      dtype='object')

In [10]:
list(gdp.items())

[('shanghai', 27466.3),
 ('beijing', 24899.3),
 ('guangzhou', 19610.9),
 ('shenzhen', 19492.4),
 ('tianjin', 17885.39),
 ('chongqing', 17558.76),
 ('suzhou', 15475.09),
 ('chengdu', 12170.2),
 ('hangzhou', 11050.5)]

In [9]:
gdp['hangzhou']=11050.5
gdp

shanghai     27466.30
beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
chongqing    17558.76
suzhou       15475.09
chengdu      12170.20
hangzhou     11050.50
dtype: float64

In [11]:
gdp[['chengdu','shanghai','tianjin']]

chengdu     12170.20
shanghai    27466.30
tianjin     17885.39
dtype: float64

In [12]:
gdp[gdp>19000]

shanghai     27466.3
beijing      24899.3
guangzhou    19610.9
shenzhen     19492.4
dtype: float64

In [13]:
g=gdp['beijing':'chengdu'] # 两端都是闭合的
g

beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
chongqing    17558.76
suzhou       15475.09
chengdu      12170.20
dtype: float64

In [14]:
g['wuhan']=11111
g

beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
chongqing    17558.76
suzhou       15475.09
chengdu      12170.20
wuhan        11111.00
dtype: float64

In [15]:
gdp

shanghai     27466.30
beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
chongqing    17558.76
suzhou       15475.09
chengdu      12170.20
hangzhou     11050.50
dtype: float64

In [18]:
gdp[4]

17885.39

In [16]:
gdp[1:5]

beijing      24899.30
guangzhou    19610.90
shenzhen     19492.40
tianjin      17885.39
dtype: float64

In [17]:
# 多级索引下Series的索引跟切片
gdp_index=[('shanghai',2015),('shanghai',2016),('beijing',2015),('beijing',2016),('guangzhou',2015),('guangzhou',2016)]
gdp_mind=pd.MultiIndex.from_tuples(gdp_index)
gdp=pd.Series([27466.3,24899.3,19610.9,19492.4,17885.39,17558.76],index=gdp_mind)
gdp

shanghai   2015    27466.30
           2016    24899.30
beijing    2015    19610.90
           2016    19492.40
guangzhou  2015    17885.39
           2016    17558.76
dtype: float64

In [19]:
g1=gdp['shanghai']
g1,type(g1)

(2015    27466.3
 2016    24899.3
 dtype: float64, pandas.core.series.Series)

In [21]:
# DataFrame对象的索引与切片
population=pd.Series([2415.27,2151.6,1270.88],index=['shanghai','beijing','guangzhou'])
population

shanghai     2415.27
beijing      2151.60
guangzhou    1270.88
dtype: float64

In [27]:
gdp=pd.Series([27466,24899,19611],index=['shanghai','beijing','guangzhou'])
gdp

shanghai     27466
beijing      24899
guangzhou    19611
dtype: int64

In [28]:
d=pd.DataFrame({'gdp':gdp,'pop':population})
d

gdp      pop
shanghai   27466  2415.27
beijing    24899  2151.60
guangzhou  19611  1270.88

In [29]:
d.values

array([[27466.  ,  2415.27],
       [24899.  ,  2151.6 ],
       [19611.  ,  1270.88]])

In [30]:
d.values[0]

array([27466.  ,  2415.27])

In [31]:
d.T

shanghai  beijing  guangzhou
gdp  27466.00  24899.0   19611.00
pop   2415.27   2151.6    1270.88

In [32]:
d['gdp']

shanghai     27466
beijing      24899
guangzhou    19611
Name: gdp, dtype: int64

In [37]:
d

gdp      pop
shanghai   27466  2415.27
beijing    24899  2151.60
guangzhou  19611  1270.88

In [46]:
d.iloc[1]

gdp    24899.0
pop     2151.6
Name: beijing, dtype: float64

In [47]:
d.iloc[1,1]

2151.6

In [51]:
d.iloc[1:3,:1]

gdp
beijing    24899
guangzhou  19611

In [54]:
d.loc['shanghai','pop']

2415.27