In [1]:
# Numpy索引与切片
import numpy as np

In [2]:
a=np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
a.ndim

3

In [4]:
np.ndim(a)

3

In [5]:
a.shape

(2, 3, 4)

In [6]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a[1][1]

array([16, 17, 18, 19])

In [8]:
a[1][1][1]

17

In [9]:
a[1,1,1]

17

In [10]:
b=np.linspace(0,100,5)
b

array([  0.,  25.,  50.,  75., 100.])

In [11]:
b.shape

(5,)

In [12]:
b[3]

75.0

In [13]:
a[1,1,1] # 的意义同a[1][1][1]，这是下标数字组的一种简化写法

17

In [14]:
a[(1,1,1)] # 同上

17

In [15]:
# ndarray可以通过索引修改相应元素
b[1]=60
b

array([  0.,  60.,  50.,  75., 100.])

In [16]:
a[1][1]=100
a

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [100, 100, 100, 100],
        [ 20,  21,  22,  23]]])

In [17]:
a[1][1][1]=666
a

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [100, 666, 100, 100],
        [ 20,  21,  22,  23]]])

In [18]:
a[1,1,2]=777
a

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [100, 666, 777, 100],
        [ 20,  21,  22,  23]]])

In [19]:
a=np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [20]:
three=a[1],a[3],a[7]
three

(2, 4, 8)

In [21]:
# 索引为一个列表时，能实现类似上述效果，但结果类型为数组不是一个元组
# 当下标为一个列表时返回的是一个新的数组
# 也就是当下标为一个list时，可以从原始ndarray中提取需要的元素组成一个新的ndarray
# 以list为下标，第一个list表示从0轴取，第二个从1轴取，以此类推
three=a[[1,3,7]]
three

array([2, 4, 8])

In [22]:
c=np.logspace(1,3,12).reshape(3,4)
c

array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [  53.36699231,   81.11308308,  123.28467394,  187.38174229],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [23]:
c[[0,1]] # 二维数组中，第一个list中代表从0轴上取元素

array([[ 10.        ,  15.19911083,  23.101297  ,  35.11191734],
       [ 53.36699231,  81.11308308, 123.28467394, 187.38174229]])

In [24]:
c[[0,2]] # 表示从0轴上取0,2的元素

array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [25]:
c[[0,2],[1,2]]  # 这个组合其实就是组合下面的，在0轴上的0,2元素中再分别取1,2元素

array([ 15.19911083, 657.93322466])

In [26]:
c[0,1],c[2,2]

(15.199110829529339, 657.9332246575682)

In [27]:
# 重复list索引取到多次同一值
c[[2,2,2]]

array([[ 284.80358684,  432.87612811,  657.93322466, 1000.        ],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

### 下标是数组

In [28]:
v=np.array([0,1,3])
print(b)
print(v)
print(b[v])

[  0.  60.  50.  75. 100.]
[0 1 3]
[ 0. 60. 75.]


In [29]:
np.array([2,3,2,3,2,3])

array([2, 3, 2, 3, 2, 3])

In [30]:
b[np.array([2,3,2,3,2,3])]

array([50., 75., 50., 75., 50., 75.])

In [38]:
b==50  # 数组判断，判断里面每个元素，得到一个bool的元组
b%2==0

array([ True,  True,  True, False,  True])

In [32]:
t=b==50
t.dtype

dtype('bool')

In [39]:
b[t]  # 根据bool数组来判断并取到相应元素

array([50.])

In [41]:
e=np.arange(10).reshape(2,5)
e  # 多维数组的bool数组索引同样遵从之前的1对1取索引的原则

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
e[np.array([True,False])]

array([[0, 1, 2, 3, 4]])

In [48]:
e[np.array([0,1]),np.array([3,4])]  # 多维ndarray的一对一取索引原则

array([3, 9])