In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.4'

In [3]:
# np.array()是创建ndarray数组的一种方式
data=np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [4]:
type(data)  # n-dimension array N维数组

numpy.ndarray

In [5]:
dir(data)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [6]:
data

array([1, 2, 3, 4, 5])

In [7]:
data.dtype  # dtype获取数组中的元素的类型

dtype('int32')

In [8]:
new_data=data.astype(np.float)  # 数组中的元素的类型必须一样，不同于list，有时我们需要修改一个数组中的元素的类型，使用astype()来修改
new_data,new_data.dtype

(array([1., 2., 3., 4., 5.]), dtype('float64'))

In [9]:
a=np.array([1,2,3])
b=np.array([1.,2.,3.,4.])  # 1. 1.0两个其实是一样的，前者简写了而已
c=np.array([1.0,2.0,3.0,4.0])
a.dtype,b.dtype,c.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [10]:
a.shape

(3,)

In [11]:
b.shape

(4,)

In [12]:
a.ndim #  返回ndarry的维度

1

In [13]:
b.ndim

1

In [14]:
a.size  # 返回nadarry的元素个数

3

In [15]:
b.size

4

In [16]:
np.array?

In [17]:
a=np.array([1,2,3,4],dtype=np.float)
a

array([1., 2., 3., 4.])

In [18]:
dc=np.array([1,2,3,4,5,6,7,8],ndmin=2)
dc

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [19]:
dc.shape


(1, 8)

In [20]:
a

array([1., 2., 3., 4.])

In [21]:
de=np.array(a,dtype=complex)
de

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [22]:
# numpy有专门的函数创建具有某些特征的ndarray
np.zeros((3,10)) # 参数是一个shape描述该ndarray的形状传入一个元组

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
da=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
da

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [24]:
da.shape

(3, 4)

In [25]:
np.zeros_like(da)  # ...._like方法创建与参数的维度相同的全0数组

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
np.ones((6,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [27]:
np.ones((1,6))

array([[1., 1., 1., 1., 1., 1.]])

In [28]:
da=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
da.shape

(4, 3)

In [29]:
np.ones(da.shape)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.ones_like(da,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
df=3.7*np.ones_like(da)
df

array([[3.7, 3.7, 3.7],
       [3.7, 3.7, 3.7],
       [3.7, 3.7, 3.7],
       [3.7, 3.7, 3.7]])

In [32]:
np.full?

In [33]:
np.full(da.shape,3.7)

array([[3.7, 3.7, 3.7],
       [3.7, 3.7, 3.7],
       [3.7, 3.7, 3.7],
       [3.7, 3.7, 3.7]])

In [34]:
# 创建对角线ndarray即主对角线为1的单位矩阵
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [35]:
np.eye(4,dtype=int,k=1) # 只能创建2维数组，且是正方形的，k代表偏移

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [36]:
np.eye(4,dtype=int,k=-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [37]:
np.identity(4)  # 此方法只能创建无偏移的单位矩阵

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.diag([1,2,3,4,5])  # 该方法功能更多，能指定对角线元素，自己确定方阵大小

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [39]:
np.diag([1,2,3,4,5,],k=2) # 还可以偏移

array([[0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [40]:
de=np.arange(16).reshape((4,4))
de

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.diag(de) # 该方法还可以获取一个方阵中的对角线元素

array([ 0,  5, 10, 15])

In [42]:
np.diag(de,k=2)  # 还可以偏移获取元素

array([2, 7])

In [43]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [44]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [45]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [46]:
my_type=np.dtype({'names':['book','version'],'formats':['S40',np.int]})  # 自定义一个ndarray的类型为my_type
my_type

dtype([('book', 'S40'), ('version', '<i4')])

In [47]:
my_books=np.array([('learn java',1),('learn python',3),('learn C++',2)],dtype=my_type)
my_books.dtype

dtype([('book', 'S40'), ('version', '<i4')])

In [48]:
my_books[1]  # 根据索引获取一个元素

(b'learn python', 3)

In [49]:
my_books['book']  # 根据类型中的name获取所有该name的元素组成的数组

array([b'learn java', b'learn python', b'learn C++'], dtype='|S40')

In [50]:
my_books['version']

array([1, 3, 2])

In [51]:
my_books[1]['book']  # 混合索引与name，先获取一个索引对应的元素，后获取其name

b'learn python'

In [52]:
my_books[1]['version']

3

In [53]:
my_books['book'][1]  # 先获取所有book name组成的数组，再按索引

b'learn python'

In [54]:
my_books['book'][1]='this is changed'  # 可通过索引修改指定元素，但不能新增

In [55]:
my_books

array([(b'learn java', 1), (b'this is changed', 3), (b'learn C++', 2)],
      dtype=[('book', 'S40'), ('version', '<i4')])

In [56]:
def foo(x):
    return x*2
np.fromfunction(foo,(5,))  # 该方法根据方法创建ndarray，方法的参数个数与ndarray的维度对应

array([0., 2., 4., 6., 8.])

In [58]:
np.fromfunction(lambda i,j:(i+1)*(j+1),(5,5),dtype=np.int)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])