In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a=np.arange(10)
b=np.reshape(a,(2,5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.shape

(10,)

In [7]:
b.shape

(2, 5)

In [8]:
c=np.reshape(b,(-1,1))  # 这里-1是一个不存在的索引，其意义就是o轴自己判断元素数量
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [9]:
np.reshape(b,(10,))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.reshape(b,(1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
# 除了使用reshape变换数组形状，还可以使用shape属性
# 这样变换的数组改变了原始数组形状，不是生成新的数组
b.shape

(2, 5)

In [12]:
b.shape=(1,10)
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
b.shape=(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# 扁平化一个数组，就是生成一个一维数组
# flatten生成新的数组，不共用一个视图
p=b.flatten()
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# 还可以使用ravel实现生成一维数组
# 该方法生成的数组与原数组共用视图
p=b.ravel()
p[0]=99
print(p)
print(b)

[99  1  2  3  4  5  6  7  8  9]
[[99  1  2  3  4]
 [ 5  6  7  8  9]]


### 组合与分割
- 水平组合

In [16]:
a=np.arange(9).reshape(3,3)
b=np.arange(12).reshape(3,4)
c=np.arange(15).reshape(3,5)
print(a)
print(b)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [17]:
np.hstack((a,b))  # 将a和b水平组合，3x3组合3x4成3x7的数组
# 传入的参数是一个元组

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [18]:
np.hstack((a,b,c))

array([[ 0,  1,  2,  0,  1,  2,  3,  0,  1,  2,  3,  4],
       [ 3,  4,  5,  4,  5,  6,  7,  5,  6,  7,  8,  9],
       [ 6,  7,  8,  8,  9, 10, 11, 10, 11, 12, 13, 14]])

- 垂直组合

In [19]:
# 垂直组合
a.shape,b.shape

((3, 3), (3, 4))

In [20]:
b2=b.T
b2.shape

(4, 3)

In [21]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
b2

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [23]:
np.vstack((a,b2))  # 垂直组合要求1轴维度相同

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

- 分割

In [24]:
a=np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
np.split(a,2,axis=1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [26]:
np.split(a,2,axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

- 增删改

In [27]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9]])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b

array([[7, 8, 9]])

In [30]:
a.ndim,b.ndim

(2, 2)

In [31]:
r=np.append(a,b,axis=0)  # 此处的append是生成新数组，不是改变原始数组
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
r=np.append(a,b)  # 如果不声明轴axis则是组合数组中的所有元素成一个新的一维数组
r

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a1=a.flatten()
a1

array([1, 2, 3, 4, 5, 6])

In [37]:
r=np.insert(a1,1,99)  # 指定索引处添加一个元素，生成一个新的数组
r

array([ 1, 99,  2,  3,  4,  5,  6])

In [49]:
np.delete(a,1,axis=0)  # 删除0轴的索引1的内容

array([[1, 2, 3]])

In [50]:
np.delete(a,1,axis=1)  # 删除1轴索引1的内容

array([[1, 3],
       [4, 6]])