In [1]:
import numpy as np

In [2]:
a=np.arange(10,20)
a

In [3]:
b=a[2:8]
b

In [4]:
b[0]=1000  # 数组的切片与原数组共用内存空间，就是使用同一个视图

In [5]:
b

In [6]:
a  # 公用一个视图

In [7]:
b=np.arange(0,60,10).reshape(-1,1)+np.arange(0,6)
b

In [8]:
b.shape

In [9]:
b.ndim

In [10]:
b[1:4]  # 多维数组切片

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [12]:
b[1:4,2:5]  # 先切0轴，再切1轴

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [22]:
b[:,[0,3]]  # 在0轴上切片取所有，在1轴上取0和3

array([[ 0,  3],
       [10, 13],
       [20, 23],
       [30, 33],
       [40, 43],
       [50, 53]])

In [36]:
b[[1,4],1:5:3]

array([[11, 14],
       [41, 44]])

In [38]:
b[:3,[0,3]]

array([[ 0,  3],
       [10, 13],
       [20, 23]])