In [1]:
import numpy as np

In [2]:
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
b=a[2:8]
b

array([12, 13, 14, 15, 16, 17])

In [4]:
b[0]=1000  # 数组的切片与原数组共用内存空间，就是使用同一个视图

In [5]:
b

array([1000,   13,   14,   15,   16,   17])

In [6]:
a  # 公用一个视图

array([  10,   11, 1000,   13,   14,   15,   16,   17,   18,   19])

In [7]:
b=np.arange(0,60,10).reshape(-1,1)+np.arange(0,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [9]:
b.shape

(6, 6)

In [8]:
b.ndim

2

In [10]:
b[1:4]  # 多维数组切片

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [11]:
b[1:4,2:5]  # 先切0轴，再切1轴

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])